
# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('tocino', ['core', 'network'])
    module.source = [
        'model/callback-queue.cc',
        'model/tocino-channel.cc',
        'model/tocino-tx.cc',
        'model/tocino-rx.cc',
        'model/tocino-net-device.cc',
        'model/tocino-flit-header.cc',
        'model/tocino-flow-control.cc',
        'model/tocino-router.cc',
        'model/tocino-dimension-order-router.cc',
        'helper/tocino-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('tocino')
    module_test.source = [
        'test/test-tocino-callbackqueue.cc',
        'test/test-tocino-flit-header.cc',
        'test/test-tocino-flitter.cc',
        'test/test-tocino-flitloopback.cc',
        'test/test-tocino-point-to-point.cc',
        'test/test-tocino-ring.cc',
        'test/test-tocino-3x3x3.cc',
        'test/tocino-test-suite.cc',
        ]

    headers = bld.new_task_gen(features=['ns3header'])
    headers.module = 'tocino'
    headers.source = [
        'model/tocino-channel.h',
        'model/tocino-net-device.h',
        'model/tocino-rx.h',
        'model/tocino-tx.h',
        'model/callback-queue.h',
        'model/tocino-address.h',
        'model/tocino-flit-header.h',
        'model/tocino-flow-control.h',
        'model/tocino-misc.h',
        'model/tocino-router.h',
        'model/tocino-dimension-order-router.h',
        'helper/tocino-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.add_subdirs('examples')

    # bld.ns3_python_bindings()

