#!/bin/bash

#../waf --run "3d-torus-bisection-bandwidth --PrintAttributes=ns3::TocinoChannel"
#../waf --run "3d-torus-bisection-bandwidth --PrintAttributes=ns3::TocinoTrafficMatrixApplication"
#../waf --run "3d-torus-bisection-bandwidth --PrintAttributes=ns3::TocinoDimensionOrderRouter"

export NS_LOG="TocinoNetDevice:TocinoChannel:TocinoSimpleArbiter"
export NS_GLOBAL_VALUE="RngRun=2"

summarizeNumber(){
    local name=$1
    
    grep "$name" tmp.txt | grep -o "[[:digit:]\.]*" > tmp2.txt

    cat tmp2.txt | sort -rn > tmp3.txt
   
    echo -en "   $name:\t"
    head -n 1 tmp3.txt | tr -d '\n'
    echo -n " ... "
    tail -n 1 tmp3.txt
}

summarizePercentage(){
    local name=$1
    
    grep "$name" tmp.txt | grep -o "[[:digit:]\.]*%" > tmp2.txt

    cat tmp2.txt | sort -rn > tmp3.txt
   
    echo -en "   $name:\t"
    head -n 1 tmp3.txt | tr -d '\n'
    echo -n " ... "
    tail -n 1 tmp3.txt
}

summarizeChannel(){
    local src=$1
    local dst=$2

    echo Links between $src and $dst
    egrep ": \(.,.,$src" chan.txt | egrep "> \(.,.,$dst" > tmp.txt
    egrep ": \(.,$src,." chan.txt | egrep "> \(.,$dst,." >> tmp.txt
    egrep ": \($src,.,." chan.txt | egrep "> \($dst,.,." >> tmp.txt
    
    #summarizeNumber "total throughput"
    #summarizeNumber "data throughput"
    #summarizeNumber "LLC throughput"

    #summarizeNumber "total bytes"
    #summarizeNumber "data bytes"
    #summarizePercentage "data bytes"
    #summarizeNumber "LLC bytes"
    #summarizePercentage "LLC bytes"

    #summarizeNumber "total flits"
    #summarizeNumber "data flits"
    #summarizePercentage "data flits"
    #summarizeNumber "LLC flits"
    #summarizePercentage "LLC flits"

    #summarizePercentage "percent busy time"
    summarizePercentage "percent data time"
    summarizePercentage "percent LLC time"
    summarizePercentage "percent idle time"
}

# max payload head flit is 40
# max payload other flit is 62
# ethernet header consumes 18 bytes per packet
# thus, --packetBytes=22 is the most that gives a single head/tail flit
# additionally (62*N)+22 gives a packet that decomposes nicely into flits
# 1510 = (62*24)+22

time ../waf --run "3d-torus-bisection-bandwidth \
    --radix=4 \
    --packetbytes=22 \
    --duration=100us \
    --ns3::TocinoTrafficMatrixApplication::MeanTimeBetweenSends=10ns \
    --ns3::TocinoTrafficMatrixApplication::MaxTimeBetweenSends=20ns \
    --ns3::TocinoNetDevice::VirtualChannels=16 \
    --ns3::TocinoNetDevice::RoundRobinVCInject=true \
    --ns3::TocinoSimpleArbiter::InterleaveVCs=true \
    --ns3::TocinoDimensionOrderRouter::OutOfOrderOK=true" \
    >out.txt 2>&1

echo

grep "Simulating" out.txt
grep "Sending" out.txt
grep "Finished after" out.txt
grep "Bisection bandwidth" out.txt

echo
    
grep "TocinoChannel:ReportStatistics" out.txt > chan.txt

summarizeChannel 0 1
summarizeChannel 1 0

summarizeChannel 1 2
summarizeChannel 2 1

summarizeChannel 2 3
summarizeChannel 3 2

summarizeChannel 3 0
summarizeChannel 0 3

echo
echo -n "Maximum m_outgoingFlits: "
grep m_outgoingFlits out.txt | cut -c 62- | egrep -o "[[:digit:]]*" | sort -rn | head -n 1

echo
echo "TocinoTestResults:"

echo -n "   Distinct lines: "
grep TocinoTestResults out.txt | wc -l

echo -n "   Max: "
grep TocinoTestResults out.txt | cut -c 62- | sort -rn | head -n 1

echo -n "   Min: "
grep TocinoTestResults out.txt | cut -c 62- | sort -rn | tail -n 1

echo
