#!/bin/bash

#../waf --run "3d-torus-bisection-bandwidth --PrintAttributes=ns3::TocinoChannel"
#../waf --run "3d-torus-bisection-bandwidth --PrintAttributes=ns3::TocinoTrafficMatrixApplication"
#../waf --run "3d-torus-bisection-bandwidth --PrintAttributes=ns3::TocinoDimensionOrderRouter"

export NS_LOG="TocinoNetDevice:TocinoChannel"

dosomething(){
    local src=$1
    local dst=$2

    grep "TocinoChannel:ReportChannelStatistics" out.txt > chan.txt

    echo Link between $src and $dst
    egrep ": \(.,.,$src" chan.txt | egrep "> \(.,.,$dst" | grep util | grep -o "[[:digit:]\.]*%" > tmp.txt
    egrep ": \(.,$src,." chan.txt | egrep "> \(.,$dst,." | grep util | grep -o "[[:digit:]\.]*%" >> tmp.txt
    egrep ": \($src,.,." chan.txt | egrep "> \($dst,.,." | grep util | grep -o "[[:digit:]\.]*%" >> tmp.txt

    cat tmp.txt | sort -rn > tmp2.txt
    
    echo -n "   Max: "
    head -n 1 tmp2.txt

    echo -n "   Min: "
    tail -n 1 tmp2.txt
}

# max payload head flit is 40
# max payload other flit is 62
# ethernet header consumes 18 bytes per packet
# thus, --packetBytes=22 is the most that gives a single head/tail flit
# additionally (62*N)+22 gives a packet that decomposes nicely into flits
# 1510 = (62*24)+22

time ../waf --run "3d-torus-bisection-bandwidth \
    --radix=4 \
    --packetbytes=22 \
    --duration=100us \
    --ns3::TocinoTrafficMatrixApplication::MeanTimeBetweenSends=10ns \
    --ns3::TocinoTrafficMatrixApplication::MaxTimeBetweenSends=20ns" \
    >out.txt 2>&1

echo

grep "Simulating" out.txt
grep "Sending" out.txt
grep "Finished after" out.txt
grep "Bisection bandwidth" out.txt

echo

dosomething 0 1
dosomething 1 0

dosomething 1 2
dosomething 2 1

dosomething 2 3
dosomething 3 2

dosomething 3 0
dosomething 0 3

grep LLC out.txt | egrep -o "[[:digit:]\.]*%" | sort -rn > llc.txt

echo
echo "LLC flit %age"

echo -n "   Max: "
head -n 1 llc.txt

echo -n "   Min: "
tail -n 1 llc.txt

echo
echo -n "Maximum m_outgoingFlits: "
grep m_outgoingFlits out.txt | cut -c 62- | egrep -o "[[:digit:]]*" | sort -rn | head -n 1

echo
echo "TocinoTestResults:"

echo -n "   Distinct lines: "
grep TocinoTestResults out.txt | wc -l

echo -n "   Max: "
grep TocinoTestResults out.txt | cut -c 62- | sort -rn | head -n 1

echo -n "   Min: "
grep TocinoTestResults out.txt | cut -c 62- | sort -rn | tail -n 1

echo
